#user  nobody;
worker_processes  3;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

stream {
    upstream ssh_backend {
        server nginx.local:22;
    }
 
    server {
        listen 22; # 你希望 Nginx 监听的端口
        proxy_pass ssh_backend; # 转发到定义的后端服务器组
    }
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 500m;


    include /etc/nginx/conf.d/*.conf; # 包含 /etc/nginx/conf.d/ 目录下的所有 .conf 文件  






}