server {
    listen       83;
    server_name  localhost;
    root         /home/docker/baidu_snuday;
    index        index.html;
    include conf.d/html.common;
}


server {
    listen       85;
    server_name  localhost;
    root         /home/docker/web-love;
    index        index.html;
    include conf.d/html.common;
}

server {
    listen       86;
    server_name  localhost;
    root         /home/docker/web-baby;
    index        index.html;
    include conf.d/html.common;
}